site_name: "MS系统帮助文档"
site_url: ""
site_description: "Document"
site_author: "yingqing.shan"
# 静态资源输出文件夹
site_dir: ./dist/docs

copyright: Copyright &copy; 2022 <a href="https://www.sayweee.com">Weee!</a>, All Rights Reserved.

#hide:
#  - navigation

edit_uri: "https://github.com/462548187/MSdocs/tree/master/docs"
theme:
    name: material  #名称
    language: zh    #语言
    features:
      - navigation.top   #返回顶端
      - navigation.expand  #侧边栏全展开
      - search.highlight    #搜索词高亮
      - search.suggest  #搜索省略回车
      - navigation.instant  #即时加载
      - navigation.tracking  #锚点跟踪
      - navigation.indexes  #次级索引页，直接将文档附加到章节，提供概览页面，在相应文件夹中创建index.md添加到导航nav开头。不兼容toc.integrate。
      - search.share  #搜索共享
      - navigation.tabs # first top-level folders are shown as tabs
      - content.code.annotate # add comment to code blocks
      - navigation.tabs # first top-level folders are shown as tabs


    palette:     #切换昼夜模式的颜色，审美差就用默认，专业点就自定义
      - media: "(prefers-color-scheme: light)"
        scheme: default  #配色方案：浅色模式
        primary: indigo  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
        accent: indigo  #强调色，默认蓝，可以交互的元素如悬停链接、按钮和滚动条
        toggle:
          icon: material/weather-sunny #图标，太阳
          name: 切换深色模式
      - media: "(prefers-color-scheme: dark)"
        scheme:  slate #配色方案：深色模式
        toggle:
          icon: material/weather-night  #图标，月亮
          name: 切换浅色模式
    font:  #字体，false 则阻止从Google加载字体
    # 内置隐私插件自动下载和自托管 Web 字体文件，无需阻止。其他字体使用附加样式表 extra.css 。
      text: Roboto  #常规字体，默认Roboto，正文、标题等，300、400、400i和700
      code: Roboto Mono  #等宽字体，默认Roboto Mono，代码块，400

    highlightjs: true
    hljs_languages:
        - yaml
        - django

    feature:
      tabs: true



nav:
    - 项目介绍: index.md
    - 通用功能:
        - 账号相关: user_manual/general/general_login.md
    - 测试跟踪:
          - 模块说明: user_manual/test_track/intro.md
          - 首页: user_manual/test_track/home.md
          - 功能用例: user_manual/test_track/test_case.md
          - 用例评审: user_manual/test_track/test_case_review.md
          - 测试计划: user_manual/test_track/test_plan.md
          - 缺陷管理: user_manual/test_track/test_defect.md
          - 报告: user_manual/test_track/test_report.md
          - 用例拓展: user_manual/test_track/test_expand.md
    - 接口测试:
          - 模块说明: user_manual/api_test/intro.md
          - 首页: user_manual/api_test/home.md
          - 接口定义: user_manual/api_test/api_definition.md
          - 接口自动化: user_manual/api_test/api_automation.md
          - 接口测试报告中心: user_manual/api_test/test_report.md
          - 用例步骤说明: user_manual/api_test/api_step.md
          - 内置函数: user_manual/api_test/functions.md
    - 项目设置:
          - 项目信息: user_manual/project_management/project_info.md
          - 项目成员: user_manual/project_management/project_user.md
          - 用户组与权限: user_manual/project_management/usergroup_permission.md
          - 项目环境: user_manual/project_management/project_environment.md
          - 文件管理: user_manual/project_management/file_management.md
          - 自定义代码片段: user_manual/project_management/customcode_snippets.md
          - 模版管理: user_manual/project_management/template_management.md
          - 消息设置: user_manual/project_management/notice_management.md
          - 操作日志: user_manual/project_management/operation_log.md
          - 应用管理: user_manual/project_management/application_management.md


plugins:
  - search # must be included at the first place
  # - tags: # we have our own internal tag feature
        # tags_file: tags.md # generated links do not work
  - awesome-pages:
      # collapse_single_pages: true # replaced by navigation.indexes
  # - section-index # must be after awesome-pages, replaced by navigation.indexes
  - git-revision-date-localized:
        enable_creation_date: false
        fallback_to_build_date: true
        type: iso_date
  - encryptcontent:
        hljs: false
        arithmatex: true
        mermaid2: true
        password_button: true
        remember_password: true
        default_expire_dalay: 24

  - exclude:
        glob:
          - '*/exclude/*'
        regex:
          - '.*\[exclude\].*'


markdown_extensions:  #推荐配置Markdown基本语法及其扩展
    - abbr #缩写或名词
    - pymdownx.snippets  #片段，将任意文件或部分内容嵌入到文档中
    - admonition  #警告或标注
    - pymdownx.details  #细节折叠
    - pymdownx.superfences  #超级围栏
    - attr_list   #属性列表（按钮-颜色图标）
    - def_list   #定义列表
    - footnotes  #行内脚注
    - meta   #元数据
    - md_in_html  #HTML 中的 Markdown
    - toc:  #目录
        toc_depth: 3 #目录深度，默认6，0则隐藏
        title: On this page  #默认值，自动获取
        permalink: true   #每个标题的末尾添加段落符号锚链接，默认false
#        permalink: ⚓︎  #每个标题的末尾添加自定义符号锚链接
        permalink_title: Anchor link to this section for reference #在悬停时显示并由屏幕阅读器阅读的锚链接的标题
        slugify: !!python/name:pymdownx.slugs.uslugify # convert title to html-compatible text
    - tables #表格（未推荐）
    - pymdownx.arithmatex:  #数学公式
        generic: true
    - pymdownx.betterem:   #粗体斜体
        smart_enable: all
    - pymdownx.caret  #插入角标符号(`^`)
    - pymdownx.mark  #双等号(`==`)
    - pymdownx.tilde  #波浪号(`~`)
    - pymdownx.critic:  #评论家(突出显示建议更改)，未推荐
  #      mode: reject #应如何解析标记，默认view查看更改，accept是接受更改，reject是拒绝更改
    - pymdownx.keys   #键盘键和组合
    - pymdownx.emoji:  #表情符号
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  #      options: #默认无
  #        custom_icons: #允许列出要在 Markdown 中使用的附加图标集的文件夹
  #          - overrides/.icons
    - pymdownx.highlight:  #代码高亮，对代码块（SuperFences）和行内代码块（InlineHilite）的语法突出显示
         linenums_style: pymdownx-inline
    - pymdownx.inlinehilite  #行内高亮
    - pymdownx.smartsymbols  #智能符号
    - pymdownx.progressbar
    - pymdownx.tabbed:  #内容选项卡
        alternate_style: true  #启用内容选项卡替代样式，必须开启
    - pymdownx.tasklist:  #任务列表
        custom_checkbox: true   #切换复选框的呈现样式，将原生复选框样式替换为漂亮的图标
  #      clickable_checkbox: true  #切换复选框是否可点击，默认false，不建议开
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - sane_lists # make better lists
    - smarty: # convert some special characters
        smart_angled_quotes: true
    - pymdownx.superfences # define code blocks and nesting of code
    - pymdownx.escapeall:
        hardbreak: true # use \ to create new line
        nbsp: true # use \<space> to create &nbsp;




extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
  analytics:
    provider: google
    property: UA-42618265-2 # or G-XXXXXXXXXX

  search:
    language: 'en,zh,jp'

  generator: false # hide the line "Made with Material for MkDocs"

extra_css:
  - css/view-bigimg.css
  - css/extra.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/view-bigimg.js
  - js/extra.js