site_name: "MeterSphere 文档"
site_url: "https://metersphere.io"
site_description: "Document"
site_author: "wangzhen"
google_analytics: ['UA-147297392-7', 'metersphere.io']

repo_name: "MeterSphere Docs"
repo_url: "https://github.com/metersphere/metersphere"

edit_uri: https://github.com/metersphere/docs/edit/master/docs/
theme: mkdocs
nav:
    - 项目介绍: index.md
    - 用户手册:
          - 通用功能: user_manual/general.md
          - 测试跟踪:
                - 模块说明: user_manual/test_track/intro.md
                - 首页: user_manual/test_track/home.md
                - 功能用例: user_manual/test_track/test_case.md
                - 用例评审: user_manual/test_track/test_case_review.md
                - 测试计划: user_manual/test_track/test_plan.md
                - 缺陷管理: user_manual/test_track/test_defect.md
                - 报告: user_manual/test_track/test_report.md
          - 接口测试:
                - 模块说明: user_manual/api_test/intro.md
                - 首页: user_manual/api_test/home.md
                - 接口定义: user_manual/api_test/api_definition.md
                - 接口自动化: user_manual/api_test/api_automation.md
                - 接口测试报告中心: user_manual/api_test/test_report.md
                - 用例步骤说明: user_manual/api_test/api_step.md
                - 内置函数: user_manual/api_test/functions.md
          - 性能测试:
                - 模块说明: user_manual/load_test/intro.md
                - 首页: user_manual/load_test/home.md
                - 性能测试: user_manual/load_test/load_test.md
                - 性能测试报告: user_manual/load_test/test_report.md
          - 报表统计:
                - 项目报表: user_manual/report_statistics/project_statistics.md
          - 项目设置:
                - 项目信息: user_manual/project_management/project_info.md
                - 项目成员: user_manual/project_management/project_user.md
                - 用户组与权限: user_manual/project_management/usergroup_permission.md
                - 项目环境: user_manual/project_management/project_environment.md
                - 文件管理: user_manual/project_management/file_management.md
                - 自定义代码片段: user_manual/project_management/customcode_snippets.md
                - 模版管理: user_manual/project_management/template_management.md
                - 消息设置: user_manual/project_management/notice_management.md
                - 操作日志: user_manual/project_management/operation_log.md
                - 应用管理: user_manual/project_management/application_management.md
          - 系统设置:
              - 模块说明: user_manual/system_management/intro.md
              - 系统: user_manual/system_management/system.md
              - 工作空间: user_manual/system_management/workspace.md

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: True
          linenums: False
    - toc:
          permalink: True
    - footnotes
    - attr_list
    - def_list
    - tables
    - abbr
    - md_in_html
    - pymdownx.extra
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.superfences
    - pymdownx.progressbar
    - lightgallery

extra_css:
    - css/extra.css


plugins:
    - search
